### ISSUE TITLE
Support & burn icon.

### ISSUE THREAD

**Issue by mnrrxyz** [JuanuMusic/posta#1]
Hi Juanu, as we talked via Discord here I bring you my proposal for support & burn button.
I look forward to your comments.

Manu.

[POSTA_BURNING_HEART.zip](https://github.com/JuanuMusic/posta/files/6785014/POSTA_BURNING_HEART.zip)

**Comment by JuanuMusic** [comment]
Nice! This looks great. I'll assign it to me and implement it asap
