### ISSUE TITLE
Add hability to get your Posta cost cover from someone else Is it possible to pay for other Posta? I mean if i want to cover the cost of someone else Posta Externally funding a post

### ISSUE THREAD

**Issue by Nachobr** [JuanuMusic/posta#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JuanuMusic** [comment]
Posting on posta is free of charge. The only payment to be done is the gas fees which are to be payed by whoever executes the post transaction, which should be the owner of the tweet.
