### ISSUE TITLE
“View on PoH” button is not workin

### ISSUE THREAD

**Issue by mnrrxyz** [JuanuMusic/posta#4]
Said button appear on every Posta profile.
When I click it I expect it to open a new tab with the PoH Profile (https://app.proofofhumanity.id/profile/[...]) but instead it open a simple HTML text page with _{"message":"Route GET:/profile/0x482c96b007ea453cb55a3dc11ceb8830e18f0639 not found","error":"Not Found","statusCode":404}_

![Captura de Pantalla 2021-07-26 a la(s) 21 27 11](https://user-images.githubusercontent.com/34553383/127075972-409b0b3c-047a-486a-9757-ce80968bf39b.png)

**Comment by stefjow** [comment]
Link should be "https://api.poh.dev/profiles/{address}".

**Comment by JuanuMusic** [comment]
Fixed! Thanks!
